<?php

namespace App\Controllers\AppSetup\Email;

use App\Controllers\BaseController;
use CodeIgniter\HTTP\ResponseInterface;
use App\Models\Auth\AuthModel;
use App\Services\EmailQueueService;
use CodeIgniter\HTTP\Response;

class EmailController extends BaseController
{
    function resetPassword()
    {
        if ($this->request->getMethod() !== 'POST') {
            if ($this->request->isAJAX()) {
                return pesan(ResponseInterface::HTTP_METHOD_NOT_ALLOWED, 'Request method not allowed');
            }

            return view('errors/html/error_405');
        }

        try {
            $authModel = new AuthModel();
            $rules = [
                'email' => [
                    'label' => 'Email address',
                    'rules' => 'required|valid_email',
                    'errors' => [
                        'required' => 'Email address is required.',
                        'valid_email' => 'Email address is invalid.'
                    ]
                ]
            ];

            validasi_form($rules);

            $email = $this->request->getPost('email');
            $email_hash = email_hash($email);

            $get_user_data = $authModel->getUserData($email_hash);
            if (!$get_user_data) {
                log_message('error', 'Email address is not registered. ' . $email_hash . ' From : ' . $this->request->getIPAddress());
                return pesan(ResponseInterface::HTTP_NOT_FOUND, 'Email address is not registered.');
            }

            $password_rules = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
            $random_password = '';

            for ($i = 0; $i < 8; $i++) {
                $random_password .= $password_rules[random_int(0, strlen($password_rules) - 1)];
            }

            $new_password = password_hash($random_password, PASSWORD_DEFAULT);

            $data_password = [
                'user_password' => $new_password,
                'remark' => "New password generated by system",
            ];

            $update_new_password = $authModel->update($get_user_data->user_id, $data_password);
            if (!$update_new_password) {
                log_message('error', 'Failed to update password. ' . $email_hash . ' From : ' . $this->request->getIPAddress());
                return pesan(ResponseInterface::HTTP_INTERNAL_SERVER_ERROR, 'Failed to process your request.');
            }

            $data = [
                'full_name' => $get_user_data->full_name,
                'new_password' => $random_password
            ];

            $body = view('Email/reset_password', $data);

            $emailService = new EmailQueueService();

            $emailService->queueEmail($email, 'Reset Password Request', $body);

            return pesan(ResponseInterface::HTTP_OK, "Email has been sent to <strong>$email</strong>. Please check your inbox or spam folder.");
        } catch (\Exception $e) {
            log_message('error', 'Unexpected error occured ' . $e->getMessage() . ' From : ' . $this->request->getIPAddress());
            return pesan(ResponseInterface::HTTP_INTERNAL_SERVER_ERROR, $e->getMessage());
        }
    }
}
